//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Efforts_Tracker.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EffortsTrackingToolEntities : DbContext
    {
        public EffortsTrackingToolEntities()
            : base("name=EffortsTrackingToolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UsersLogin> UsersLogins { get; set; }
        public virtual DbSet<TicketCategorisation> TicketCategorisations { get; set; }
        public virtual DbSet<TicketCategorisationDetail> TicketCategorisationDetails { get; set; }
        public virtual DbSet<TicketsMaster> TicketsMasters { get; set; }
        public virtual DbSet<vw_TicketsDetails> vw_TicketsDetails { get; set; }
        public virtual DbSet<AdhocRequest> AdhocRequests { get; set; }
        public virtual DbSet<Meeting> Meetings { get; set; }
    }
}
