//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Efforts_Tracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketsMaster
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> TicketType { get; set; }
        public string TicketNumber { get; set; }
        public string WorkedDate { get; set; }
        public string TotalHours { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> RequestType { get; set; }
    }
}
